[[constraint]]
  branch = "master"
  name = "github.com/alecthomas/jsonschema"

[[constraint]]
  branch = "master"
  name = "github.com/intel-go/fastjson"

[[constraint]]
  branch = "master"
  name = "github.com/Aarabika/context"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.1.0"
